### ISSUE TITLE
Serial port monitor blocks the registration_helper.py script

### ISSUE THREAD

**Issue by scarolan** [m5stack/Core2-for-AWS-IoT-EduKit#27]
This may be obvious, but if you have the serial port monitor running (for example, if you followed the first part of the tutorial and left it running), the serial port will be blocked, preventing you from running the script to register your device.  You might want to mention this in the docs.

**Comment by rashedtalukder** [comment]
The dilemma is always how much to include since many human beings have a tendency to not read thoroughly. Writing more only exacerbates the problem. The instructions say to close the serial monitor, and then erase the flash before continuing to blinky. Following those instructions would not give you the error that you're seeing.

BTW, by not erasing the flash earlier, you might have issues later on since it uses different partition tables.
