### ISSUE TITLE
Necessary permissions are unclear at Blinky and/or subsequent story

### ISSUE THREAD

**Issue by tokuhira** [m5stack/Core2-for-AWS-IoT-EduKit#31]
AWS IoT EduKit > Blinky Hello World > Prerequisites

In "AWS CLI Configuration" section, the authority required to carry out the description "you will need to give necessary permissions to your IAM user." is not specified. I would like you to present a simple but compact authority set instead of a huge comprehensive authority.

**Comment by rashedtalukder** [comment]
In order to that, we would have to duplicate the full installation instructions and maintain our own set. Since the AWS CLI is subject to roadmap changes that we cannot track effectively, we cannot synchronize that at a level I am comfortable with. We require all users to _not_ use a production AWS account and have the disclaimer in the introduction. 

I see the merit and I would do this if it was more easily feasible. If this request comes up again, we will consider reducing the scope of the IAM policy for the user as an optional instruction after the official installation.
